<a href="https://colab.research.google.com/github/Python-Puppet/Python-Basics/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
ar0 = list(range(10))
ar0

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
ar1 = np.array(range(10))
ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### numpy array attributes

In [6]:
ar1.shape, ar1.ndim, ar1.size

((10,), 1, 10)

In [7]:
ar2 = np.array((range(5), range(0,10,2)))
ar2

array([[0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8]])

In [8]:
ar2.shape, ar2.ndim, ar2.size

((2, 5), 2, 10)

### Indexing
is similar to lists in Python.
Find the notebook on Lists in python [here](https://colab.research.google.com/drive/1eyQmYDv4OCOBFxIOBvO9nbfdMREnpQyt?authuser=2#scrollTo=Rrh6zINHJOv1)

### Reshaping of Arrays

In [9]:
straight = np.array(range(1,10))
straight

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
box = straight.reshape(3,3) #note that the sizes must match
box

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Concating


*   concatenate
*   vstack
*   hstack



In [11]:
l1 = [1,2,3]
l2 = [4,5,6]
l3 = ['a','b','c']


In [12]:
l1+l2

[1, 2, 3, 4, 5, 6]

In [13]:
l1+l2+l3

[1, 2, 3, 4, 5, 6, 'a', 'b', 'c']

In [14]:
n1 = np.array([1,2,3])
n2 = np.array([4,5,6])
n3 = np.array(['a','b','c'])

In [15]:
n1+n2+n3

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('int64'), dtype('<U1')) -> None

In [16]:
# np.concatenate(n1, n2, n3) # will throw error
np.concatenate([n1, n2, n3])

array(['1', '2', '3', '4', '5', '6', 'a', 'b', 'c'], dtype='<U21')

In [17]:
np.hstack([n1, n2, n3])

array(['1', '2', '3', '4', '5', '6', 'a', 'b', 'c'], dtype='<U21')

In [18]:
np.vstack([n1, n2, n3])

array([['1', '2', '3'],
       ['4', '5', '6'],
       ['a', 'b', 'c']], dtype='<U21')

### Splitting

In [19]:
nums = np.arange(10)
nums

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.split(nums,[2,4])

[array([0, 1]), array([2, 3]), array([4, 5, 6, 7, 8, 9])]

In [21]:
nums_reshaped = nums.reshape([5,2])
nums_reshaped

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [22]:
np.vsplit(nums_reshaped,[1,2])

[array([[0, 1]]),
 array([[2, 3]]),
 array([[4, 5],
        [6, 7],
        [8, 9]])]

In [23]:
np.hsplit(nums_reshaped,[1,2])

[array([[0],
        [2],
        [4],
        [6],
        [8]]),
 array([[1],
        [3],
        [5],
        [7],
        [9]]),
 array([], shape=(5, 0), dtype=int64)]

### Useful functions

In [24]:
nums = np.array([100,10,20,5,30,40])
nums

array([100,  10,  20,   5,  30,  40])

In [25]:
np.min(nums), np.max(nums), np.sum(nums), np.mean(nums)

(5, 100, 205, 34.166666666666664)

In [26]:
nums_sorted = np.sort(nums)
nums_sorted

array([  5,  10,  20,  30,  40, 100])

In [27]:
nums

array([100,  10,  20,   5,  30,  40])

In [28]:
nums.sort()
nums

array([  5,  10,  20,  30,  40, 100])

In [29]:
nums = np.array([100,10,20,5,30,40])
nums

array([100,  10,  20,   5,  30,  40])

In [30]:
nums.argsort()

array([3, 1, 2, 4, 5, 0])

### Useful numpy arrays

In [31]:
one = np.ones([3,3])
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
zero =np.zeros([3,3])
zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Broadcasting

In [33]:
one+2

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [34]:
one+np.array([3,3,3])

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [35]:
one.shape, np.array([3,3,3]).shape

((3, 3), (3,))

In [ ]:
#shapes need to match to broadcast
# one+np.array([3,3]) will throw error